[connections.postgresql]
dialect = "postgresql"
host = "ep-quiet-feather-a4yxx4vt-pooler.us-east-1.aws.neon.tech"
port = "5432"
database = "neondb"
username = "mohamedsamake8322"
password = "78772652Sama#"
sslmode = "require"

[authentication]
jwt_secret_key = "3796ab8ae7d93e9a1498f152e7ac536b8ea590beaf6aae9f4431dbc64059367a"
connections.postgresql.database = "neondb"
connections.postgresql.username = "mohamedsamake8322"
connections.postgresql.password = "78772652Sama#"
connections.postgresql.host = "ep-quiet-feather-a4yxx4vt-pooler.us-east-1.aws.neon.tech"
connections.postgresql.port = "5432"
connections.postgresql.sslmode = "require"
authentication.jwt_secret_key = "3796ab8ae7d93e9a1498f152e7ac536b8ea590beaf6aae9f4431dbc64059367a"